services:
  postgres:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=graphql_security_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'